FROM arm64v8/alpine:3.5

ENV QEMU_EXECVE 1
COPY bin/ /usr/bin/
COPY . /usr/bin

RUN [ "qemu-arm-static", "/bin/sh", "-c", "ln -s resin-xbuild /usr/bin/cross-build-start; ln -s resin-xbuild /usr/bin/cross-build-end; ln /bin/sh /bin/sh.real" ]
